name: CI

on:
  push:
    branches: [main]
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/ruff-action@v3
      - run: ruff check --fix
      - run: ruff format --check --diff

  test-windows:
    runs-on: windows-latest
    name: Pytest on Windows
    defaults:
      run:
        shell: bash -el {0}

    env:
      PYTHONIOENCODING: utf-8 # https://github.com/Textualize/rich/issues/212
      PYTHONUTF8: 1 # from https://github.com/ndonkoHenri/flet-github-action-workflows/blob/main/.github/workflows/windows-build.yml#L29C3-L29C16
      # below line is legacy line, but I'm keeping it here for reference to know where the packages are installed
      # GST_PLUGIN_PATH: "D:\\a\\open-world-agents\\open-world-agents\\projects\\owa-env-gst\\gst-plugins"

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Setup Conda Environment
        uses: ./.github/actions/setup-conda-env
        with:
          os: windows
          cache-number: '0'
          cache-suffix: 'test-windows' # same as job name
          environment-file: 'environment.yml'

      - name: Setup uv
        uses: ./.github/actions/setup-uv
        with:
          show-uv-cache-info: 'true'

      - name: Install dependencies
        run: vuv install --dev

      - name: Run pytest
        run: pytest
