name: Release

on:
  push:
    branches: [main]
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  release-ocap:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash -el {0}

    env:
      PYTHONIOENCODING: utf-8 # https://github.com/Textualize/rich/issues/212

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Setup Conda Environment
        uses: ./.github/actions/setup-conda-env
        with:
          os: windows
          cache-number: '0'
          cache-suffix: 'release-ocap' # same as job name
          environment-file: 'environment.yml'

      - name: Setup uv
        uses: ./.github/actions/setup-uv
        with:
          show-uv-cache-info: 'true'

      - name: Install conda-pack
        run: uv pip install conda-pack

      - name: Generate Release Files
        run: |
          # Step 1: Install ocap
          uv pip install .
          
          # Step 2: Run `conda pack -n owa`
          # NOTE: `conda-pack` requires the packages to be installed without `--editable` flag.
          conda-pack -n owa --output scripts/release/env.tar.gz
          echo "Packed conda environment."
      
      - name: Test whether ocap works well
        run: ocap --help

      - name: Upload Release Files
        uses: actions/upload-artifact@v5
        with:
          name: ocap
          path: |
            scripts/release/env.tar.gz
            scripts/release/run.bat
            scripts/release/restore_ocap.py